import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideNav from '@/app/ui/components/sidenav'
import { ThemeProvider } from '@/app/providers/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Inventory Dashboard',
    default: 'Inventory Dashboard',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-screen overflow-hidden' suppressHydrationWarning>
      <body
        className={`${inter.className} h-screen overflow-hidden md:p-4 flex`}
        style={{ backgroundColor: 'var(--color-background)', color: 'var(--color-foreground)' }}
      >
        <ThemeProvider>
          <div
            className='h-full w-full md:rounded-3xl overflow-hidden relative'
            style={{ backgroundColor: 'var(--color-dark)' }}
          >
            <div className='hidden md:block border-0 rounded absolute blur-3xl w-[118px] h-[102px] top-[-59px] left-[-51px] opacity-60' style={{ background: 'radial-gradient(var(--gradient-start), var(--gradient-end))' }}></div>
            <div className='hidden md:block border-0 rounded absolute blur-3xl w-[118px] h-[102px] bottom-[-59px] left-[-51px] opacity-60' style={{ background: 'radial-gradient(rgba(197, 138, 66, 0.6), rgba(197, 138, 66, 0))' }}></div>
            <div className='flex flex-col md:grid md:grid-cols-main-layout h-full'>
              <div className='relative z-[100] overflow-visible'>
                <SideNav />
              </div>
              <div className='flex-1 overflow-x-hidden overflow-y-auto'>
                {children}
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
