import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideNav from '@/app/ui/components/sidenav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Inventory Dashboard',
    default: 'Inventory Dashboard',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='min-h-screen'>
      <body className={`${inter.className} min-h-screen md:p-4 bg-light flex dark:bg-black text-black  dark:text-primary`}>
        <div className='h-auto w-full bg-gray-300 dark:bg-dark md:rounded-3xl md:overflow-hidden relative'>
          <div className='hidden md:block border rounded absolute blur-3xl w-[118px] h-[102px] bg-radial-gradient-blue top-[-59px] left-[-51px]'></div>
          <div className='hidden md:block border rounded absolute blur-3xl w-[118px] h-[102px] bg-radial-gradient-yellow bottom-[-59px] left-[-51px]'></div>
          <div className='grid grid-cols-main-layout h-full'>
            <SideNav />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
